- name: variables from PLAY level
  hosts: localhosts
  vars:
    course: "DevOps"
    Trainer: "sivakumar"
    Duration: "110 Hrs"

  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "hi,i am learning {{course}}, Traner is {{Trainer}}, Duration is {{Duration}}"
