- name: variables from PLAY level
  hosts: localhost
  vars:
    course: "Devops"
    Trainer: "Sivakumar"
    Duration: "110Hrs"
  task:
  - name: check variables
    ansible.builtin.debug:
      msg: "hi, Iam learing {{course}}" ,trainer is {{Trainer}} , Duration is {{Duration}}
