- name: variables from PLAY level
  hosts: localhost
  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "hi, Iam learing {{course}} ,trainer is {{Trainer}} , Duration is {{Duration}}""
